---
title: "R package development workshop"
---

Welcome to the R package development workshop!

This is a two-day workshop, taking place at The University of Warwick, June 26th-27th, 2024.

It is aimed primarily at graduate students in the Department of Statistics, but open to all interested members of the university, space permitting. 

Please see the [join](join.qmd) page for details on how to sign-up for the course.

## Syllabus overview

This is a hands-on workshop covering the entire process of creating an R package: including functions and data, checking and testing, all levels of documentation, publication and maintenance. The final session covers the advanced topic of using Rcpp code in a package.

All slides and further resources can be accessed from the [content](content.qmd) page and also via the [schedule](schedule.qmd). 

## Session details

{{< fa calendar >}} &nbsp; June 26th-27th, 2024

{{< fa clock >}} &nbsp; 10:30--16:30

{{< fa location-dot >}} &nbsp; Room A1.01, Zeeman Building, University of Warwick

{{< fa utensils >}} &nbsp; Lunch provided each day

{{< fa calendar-alt >}} &nbsp; See the full [schedule](schedule.qmd).

## Instructor details

{{< fa user >}} &nbsp; [Ella Kaye](https://warwick.ac.uk/ellakaye) and [Heather Turner](https://warwick.ac.uk/heatherturner)

{{< fa envelope >}} &nbsp; [ella.m.kaye@warwick.ac.uk](mailto:ella.m.kaye@warwick.ac.uk) and [h.turner.1@warwick.ac.uk](mailto:h.turner.1@warwick.ac.uk)

## Prerequistes

Please see the [prerequisites](prerequisites.qmd) page for details on getting set up in advance of the first session.
