---
title: May-July 2026, cohort 2
---

## Join

::: {.callout-note}
Please note this workshop consists of a series of **five** sessions, which build on each other.
Luma does not offer the ability to schedule a series of recurring events. 
To sign up for the series, please click on the 'Register on Luma' button below, which will take you to the calendar, 
and make sure you register for all five **cohort 2** sessions (noting that there are also five sessions in the calendar for [cohort 1](may-july-2026-cohort-1.qmd)).
:::

[Register on Luma](https://luma.com/Forwards_Package_Development){.btn .btn-primary target="_blank"}

## Instructors

{{< fa user >}}   [Joyce Robbins](https://datascience.columbia.edu/people/joyce-robbins/), [Jesi Formoso](https://jformoso.github.io/) and [Heather Turner](https://heatherturner.net).

{{< fa envelope >}}   [h.l.turner\@bham.ac.uk](mailto:h.l.turner@bham.ac.uk)

## Schedule

{{< fa calendar >}} &nbsp; Every other **Wednesday**, starting May 20th

{{< fa clock >}} &nbsp; {{< localtime 2026-05-20 14:00 UTC format="%H:%M" >}}-{{< localtime 2026-05-20 16:00 UTC format="%H:%M %Z" >}} (in your local timezone).

| Module | Date | 
|----|----|
| [Package foundations](../modules/01-package-foundations/index.qmd) | May 20th |
| [Function documentation and dependencies](../modules/02-documentation/index.qmd) | June 3rd | 
| [Packaging data; Testing](../modules/03-data-testing/index.qmd) | June 17th | 
| [Package check and documentation](../modules/04-check-package-documentation/index.qmd) | July 1st | 
| [Publication and maintenance](../modules/05-publication-maintenance/index.qmd) | July 15th | 

## Welcome and introduction

Here's a link to the [slides](may-july-2026-cohort-2.qmd){target="_blank"} in a new window. 

Here are the slides embedded:

<iframe class="slide-deck ar16x9" src="may-july-2026-cohort-2-intro.html" title="01-welcome slides">
</iframe>

