---
title: May-July 2026, cohort 1
---

## Join

[Register on Luma](URL){.btn .btn-primary target="_blank"}

## Instructors

{{< fa user >}}   [Ella Kaye](https://ellakaye.co.uk), [Pao Corrales](https://paocorrales.github.io/), and [Elio Campitelli](https://eliocamp.github.io).

{{< fa envelope >}}   [e.kaye.1\@bham.ac.uk](mailto:e.kaye.1@bham.ac.uk)

## Schedule

{{< fa calendar >}} &nbsp; Every other **Monday**, starting May 18th

{{< fa clock >}} &nbsp; {{< localtime 2026-05-18 10:00 UTC format="%H:%M" >}}-{{< localtime 2026-05-18 12:00 UTC format="%H:%M %Z" >}} (in your local timezone).


| Module | Date | Lead | Facilitator |
|----|----|----|----|
| [Package foundations](../modules/01-package-foundations/index.qmd) | May 18th | Ella | Pao |
| [Function documentation and dependencies](../modules/02-documentation/index.qmd) | June 1st | Ella | Elio |
| [Packaging data; Testing](../modules/03-testing/index.qmd) | June 15th | Ella | Pao |
| [Package check and documentation](../modules/04-check-package-documentation/index.qmd) | June 29th | Pao | Elio |
| [Publication and maintenance](../modules/05-data-publication-maintenance/index.qmd) | July 13th | Pao | Elio |

## Welcome and introduction

Here's a link to the [slides](may-july-2026-cohort-1-intro.qmd){target="_blank"} in a new window. 

Here are the slides embedded:

<iframe class="slide-deck ar16x9" src="may-july-2026-cohort-1-intro.html" title="01-welcome slides">
</iframe>

